<p style="text-align:center">
PSY 394U <b>Python Coding for Psychological Sciences</b>, Fall 2017

<img src="https://www.python.org/static/community_logos/python-logo-master-v3-TM.png" alt="Python logo" width="200">
</p>

<h1 style="text-align:center"> NumPy & arrays </h1>

<h4 style="text-align:center"> November 2 - 7, 2017 </h4>
<hr style="height:5px;border:none" />
<p>

# 1. Creating an array
<hr style="height:1px;border:none" />

An array is a data type available in **`NumPy`**. It is similar to a list, but much more
versatile than a list, and especially useful for scientific data.

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

Note that when we import **`numpy`**, we assign a name **`np`**, so that we don't have to
type `numpy` every time we call a function in the `numpy` module. An array can be
converted to a list, or vice versa.

In [2]:
list(a)

[1, 2, 3, 4, 5]

In [3]:
b = [10, 9, 8, 7, 6]
np.array(b)

array([10,  9,  8,  7,  6])

An array can be two dimensional. For example,

In [4]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

You can examine the shape of an array using the **`ndim`** method (to examine
dimension), the **`shape`** method (to examine the size in each dimension), and the
**`size`** method (to examine the total number of elements).

In [5]:
c.ndim

2

In [6]:
c.shape

(4, 3)

In [7]:
c.size

12

This tells us that the array `c` is two-dimensional, with 4 rows and 3 columns, and
has 12 elements.