<p style="text-align:center">
PSY 394U <b>Python Coding for Psychological Sciences</b>, Fall 2017

<img src="https://www.python.org/static/community_logos/python-logo-master-v3-TM.png" alt="Python logo" width="200">
</p>

<h1 style="text-align:center"> NumPy & arrays </h1>

<h4 style="text-align:center"> November 2 - 7, 2017 </h4>
<hr style="height:5px;border:none" />
<p>

# 1. Creating an array
<hr style="height:1px;border:none" />

An array is a data type available in **`NumPy`**. It is similar to a list, but much more
versatile than a list, and especially useful for scientific data.

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

Note that when we import **`numpy`**, we assign a name **`np`**, so that we don't have to
type `numpy` every time we call a function in the `numpy` module. An array can be
converted to a list, or vice versa.

In [3]:
list(a)

[1, 2, 3, 4, 5]

In [4]:
b = [10, 9, 8, 7, 6]
np.array(b)

array([10,  9,  8,  7,  6])

An array can be two dimensional. For example,

In [5]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

You can examine the shape of an array using the **`ndim`** method (to examine
dimension), the **`shape`** method (to examine the size in each dimension), and the
**`size`** method (to examine the total number of elements).

In [6]:
c.ndim

2

In [7]:
c.shape

(4, 3)

In [8]:
c.size

12

This tells us that the array `c` is two-dimensional, with 4 rows and 3 columns, and
has 12 elements.

In practice, you usually do not enter elements one by one. Here are some useful
functions. First, the **`arange()`** function works just like the `range()` function.
The difference is that it can produce a sequence of non-integers.

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,1.875,0.125)

array([ 0.   ,  0.125,  0.25 ,  0.375,  0.5  ,  0.625,  0.75 ,  0.875,
        1.   ,  1.125,  1.25 ,  1.375,  1.5  ,  1.625,  1.75 ])

Another useful function is the **`linspace()`** function. This function splits an
interval into segments of equal widths. For example,

In [11]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [12]:
np.linspace(0,1,6)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [13]:
np.linspace(0,1,7)

array([ 0.        ,  0.16666667,  0.33333333,  0.5       ,  0.66666667,
        0.83333333,  1.        ])

You can also create a 2D array of ones or zeros with the **`ones()`** and **`zeros()`**
functions, respectively.

In [14]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [15]:
np.ones([4,2])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [16]:
np.zeros((4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

Note that the input for these functions have to be a *tuple* (e.g., (3, 3)) or a *list*
(e.g., [3, 3]).